services:
  traefik:
    name: ingress
    namespace: ingress
    autosync: true
    path: traefik
    repoURL: https://github.com/udhayd/argocd-apps
    targetRevision: master

  argocd:
    name: argocd
    namespace: argocd
    autosync: true
    path: argocd
    repoURL: https://github.com/udhayd/argocd-apps
    targetRevision: master

  services:
    name: services
    namespace: services
    autosync: true
    path: . 
    repoURL: https://github.com/udhayd/argocd-apps
    targetRevision: master
