{{- range $k, $v := $.Values.services }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $v.name }}"
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "{{ $v.namespace }}"
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "{{ $v.path }}"
    repoURL: "{{ $v.repoURL }}"
    targetRevision: "{{ $v.targetRevision }}"
  {{- if eq (toString $v.autosync) "true" }} 
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
